SuperMarket/app/urls.py
from django.urls import path
from django.views.generic.base import RedirectView

from .view_sets import front_site, message_handler, login_handler
from .view_sets.background import accounts, providers, goods, purchase, records, sales, index

urlpatterns = [
    path('favicon.ico', RedirectView.as_view(url='/static/hs.ico')),

    path('', front_site.index, name='index'),
    path('all/', front_site.all, name='goods_all'),
    path('detail/', front_site.detail, name='goods_detail'),
    path('about/', front_site.about, name='about'),
    path('feedback/', front_site.feedback, name='feedback'),
    path('send_feedback/', message_handler.send_feedback, name='send_feedback'),

    path('login/', login_handler.login, name='login'),
    path('logout/', login_handler.logout, name='logout'),

    # 账号管理
    path('account_all/', accounts.account_all, name='account_all'),
    path('account_add/', accounts.account_add, name='account_add'),
    path('account_exist/', accounts.account_exist, name='account_exist'),
    path('account_update/', accounts.account_update, name='account_update'),
    path('account_delete/', accounts.account_delete, name='account_delete'),
    path('profile/', accounts.profile, name='profile'),
    # 供应商管理
    path('provider/', providers.provider_all, name='providers'),
    path('provider_add/', providers.provider_add, name='provider_add'),
    path('provider_delete/', providers.provider_delete, name='provider_delete'),
    path('provider_update/', providers.provider_update, name='provider_update'),
    # 商品管理
    path('goods/', goods.goods_all, name='goods_manage'),
    path('good_lower/', goods.good_lower, name='good_lower'),
    path('good_edit/', goods.good_edit, name='good_edit'),
    path('limit/', goods.goods_all, name='limit'),
    path('good_remove/', goods.good_remove, name='good_remove'),
    # 进货管理
    path('purchase/', purchase.purchase, name='purchase'),
    path('purchase_supplement/', purchase.purchase_supplement, name='purchase_supplement'),
    # 记录查询
    path('records/', records.records, name='records'),
    path('storage/', records.storage, name='storage'),

    path('messages/', message_handler.show_messages, name='messages'),
    path('new_messages/', message_handler.new_messages, name='new_messages'),
    path('new_notifications/', message_handler.new_messages, name='new_notifications'),
    path('is_read/', message_handler.new_messages, name='is_read'),
    path('send_note/', message_handler.send_note, name='send_note'),
    # 销售台
    path('sale/', sales.sale, name='sale'),
    path('sale_record/', sales.sale_record, name='sale_record'),
    # 销售概况
    path('view_all/', index.view_all, name='view_all'),

]

SuperMarket/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('home.urls')),
    path('', include('app.urls')),
]

SuperMarket/app/models.py
from django.db import models


# 管理员表
class Manager(models.Model):
    account = models.CharField(max_length=20)   # 登陆账号
    pwd = models.CharField(max_length=40)       # 登陆密码

    name = models.CharField(max_length=20)      # 管理员名字，记录操作
    gender = models.IntegerField(default=0)     # 0女 1男
    phone = models.CharField(max_length=11)     # 电话，联系
    authority = models.IntegerField(default=0)  # 权限，[0]超级管理员，[1]经理，[2]采购员，[3]售货员

    isDelete = models.BooleanField(default=0)   # 逻辑删除 0存在 1删除


# 供应商表
class Provider(models.Model):
    name = models.CharField(max_length=20)
    address = models.CharField(max_length=40)
    phone = models.CharField(max_length=11)

    isDelete = models.BooleanField(default=False)


# 商品表
class Goods(models.Model):
    name = models.CharField(max_length=20)       # 图片命名为0_name.png??
    # img = models.ImageField(upload_to='goods_img/')
    sale_price = models.FloatField()             # 出售价格
    cost_price = models.FloatField()             # 进货价格
    weight = models.FloatField()                 # 重量
    sort = models.IntegerField()                 # 类别：[0]零食饮料 [1]生鲜果蔬 [2]粮油副食 [3]清洁用品 [4]家居家电
    # location = models.IntegerField()             # 所在超市 4东、2三、1一，[0] [3]一饭三饭 [5]一饭东区 [6]三饭东区 [7]全有

    produce_date = models.DateField()            # 生产日期
    limit_date = models.DateField()              # 使用期限
    # preserve = models.IntegerField()             # 保质期

    # isHot = models.IntegerField(null=True)       # 如果不为0或null，则往上增加，作为热度指标
    # isCheap = models.IntegerField(null=True)     # 热度长时间为0或null，或者临期，则考虑降价出售
    lower = models.FloatField(default=0)         # 改成浮点，后台输入数字，然后定义减法降价

    provider = models.ForeignKey(Provider, on_delete=True)

    isDelete = models.BooleanField(default=False)


# 记录表  # 都可为null，用一张表存储进货和出货两种记录
class Record(models.Model):
    location = models.IntegerField()                 # 发生的超市位置
    date = models.DateField(auto_now=True)           # 发生的日期
    purchase_num = models.IntegerField(null=True)    # 进货数量  # 库存=所有进货记录-所有出售记录
    sale_num = models.IntegerField(null=True)        # 出售数量  # 销量=所有出售记录
    withdraw_num = models.IntegerField(null=True)                 # 下架退回  # 好像没有用到的地方

    goods = models.ForeignKey(Goods, on_delete=True)


# 消息表  # 反馈/系统消息/职员消息
class Message(models.Model):
    time = models.DateTimeField(auto_now=True)   # 消息发送时间  # auto_now只有一次，auto_now_add可以继续添加新的值，即改变值
    type = models.IntegerField()    # [0]系统消息，由管理员发送，或者自动发送，全员接收 [1]反馈消息
    content = models.TextField()
    contact = models.CharField(max_length=20)    # 联系方式，同下
    name = models.CharField(max_length=20)       # 姓名，在js控制，如果输入为空则存为匿名用户

    isRead = models.BooleanField(default=False)


# 登陆，进货-->
# 基本功能要求：
# 1.	商品的进、出货操作；
# 2.	进、出货记录和库存记录的查询；
# 3.	商品信息管理；
# 4.	系统设置。
# 5.	系统登陆与注销
# 根据职位不同，分别具有如下功能：
# 1)	销售员：商品查价、出售、退货、账单记录等；-------------商品表：增删改
# 2)	经理：账本管理、调整商品价格、上下架、库存记录查询等；
# 3)	采购员：对库存进行增删改，进出货记录等；
# 4)	系统管理员：分配系统账号和权限等。

SuperMarket/templates/home/about.html
{% extends "home/all.html" %}

{% block title %}
-关于
{% endblock %}

{% block loc %}
        关于
{% endblock loc %}
{% block main %}

	<!-- about-slid -->
	<div class="about-slid agileits-w3layouts">
		<div class="container">
			<div class="about-slid-info">
				<h2>优选百货，品质生活</h2>
				<p>每天都会进行一次上架商品的检查，每周都会进行一次库存货物的更新，保证您的购物品质和体验</p>
			</div>
		</div>
	</div>
	<!-- //about-slid -->

<!-- about -->
	<div class="about">
		<div class="container">
			<h3 class="w3_agile_header">ABOUT</h3>
			<div class="about-agileinfo w3layouts">
				<div class="col-md-8 about-wthree-grids grid-top">
					<h4>对于网站前端的说明：</h4>
                    <p>本网站的前端展示内容，基本来源于右边显示的网站，是已经过稍加修改的。
                    如果有侵犯到您的权益，请在下方反馈入口进行反馈，并留下您的联系方式，我会在收到消息之后的三日内与您取得联系。谢谢！
                    </p>
                    <div class="about-w3agilerow">
						<div class="about-slid agileits-w3layouts">
                    </div>
						<div class="clearfix"> </div>
					</div>
                    <br>
					<h4>Statement：</h4>
                    <p>The display pages of this site are basically from the site on the right side, which was slightly modified.
                        If there is any violation of your rights and interests, please feedback through the entry-link below
                        and leave your contact information, I will get in touch with you within three days after receiving the message. Thanks!
                    </p>
				</div>
				<div class="col-md-4 about-wthree-grids">
					<div class="offic-time">
						<div class="time-top">
							<h4>网站前端素材：</h4>
						</div>
						<div class="time-bottom">
							<h5>来自  ——  模板之家</h5>
							<p>www.cssmoban.com </p>
						</div>
					</div>
                    <!--最近评价-->
					<div class="testi">
						<a href="/feedback"> <h3 class="w3_agile_header">反馈 &amp; 评价</h3></a>
						<!--//End-slider-script -->
						<script src="../../../static/home/js/responsiveslides.min.js"></script>
						 <script>
							// You can also use "$(window).load(function() {"
							$(function () {
							  // Slideshow 5
							  $("#slider5").responsiveSlides({
								auto: true,
								pager: false,
								nav: true,
								speed: 500,
								namespace: "callbacks",
								before: function () {
								  $('.events').append("<li>before event fired.</li>");
								},
								after: function () {
								  $('.events').append("<li>after event fired.</li>");
								}
							  });

							});
						  </script>
						<div  id="top" class="callbacks_container">
							<ul class="rslides" id="slider5">
                                {% for m in message %}
                                <li>
									<div class="testi-slider">
										<h4>" {{ m.content }} "</h4>
{#										<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eu magna dolor, quisque semper.</p>#}
										<div class="testi-subscript">
											<p><a>{{ m.name }}</a></p>
											<span class="w3-agilesub"> </span>
										</div>
									</div>
								</li>
                                {% endfor %}
							</ul>
						</div>
					</div>
                    <!--//最近评价-->
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>
	<!-- //about -->
{% endblock %}

SuperMarket/templates/home/all.html
{% extends "home/index.html" %}
{% load my_tags %}
{% block title %}
-
                    {% if flag == 1 %}
                        {{ good_list.0.sort|safe|get_simple_sort }}
                    {% elif flag == 0 %}
                        搜索
                    {% else %}
                        全部商品
                    {% endif %}
{% endblock %}

{#可以作为子模板，给分类使用#}
{#似乎……没必要，在视图返回不同的数据就行了#}
{% block location %}
    <div class="breadcrumbs">
		<div class="container">
			<ol class="breadcrumb breadcrumb1 animated wow slideInLeft" data-wow-delay=".5s">
				<li><a href="{% url 'index' %}"><span class="glyphicon glyphicon-home" aria-hidden="true"></span>首页</a></li>
				<li class="active">
				{% block loc %}
                    {% if flag == 1 %}
                        {{ good_list.0.sort|safe|get_simple_sort }}
                    {% elif flag == 0 %}
                        搜索
                    {% else %}
                        全部商品
                    {% endif %}
				{% endblock loc %}
</li>
			</ol>
		</div>
	</div>
{% endblock location%}
{% block main %}
    <div class="products">
		<div class="container">
			<div class="col-md-4 products-left">
				<div class="categories">
					<h2>推荐</h2>
					<ul class="cate">
						<li><a href="#"><h4>热卖</h4></a></li>
							<ul>
                                {% for num in hot_keys %}
								    <li><a href="/detail?id={% get_object_id dict num %}"><i class="fa fa-arrow-right" aria-hidden="true"></i>{% get_object_name dict num %}</a> </li>
                                {% endfor %}
							</ul>
						<li><a href="#"><h4>特价</h4></a></li>
							<ul>
                                {% for g in cheap_list %}
								    <li><a href="/detail?id={{ g.id }}"><i class="fa fa-arrow-right" aria-hidden="true"></i>{{ g.name }}</a> </li>
                                {% endfor %}
							</ul>
						<li><a href="#"><h4>新品</h4></a></li>
							<ul>
                                {% for r in new_list %}
								    <li><a href="/detail?id={{ r.goods.id }}"><i class="fa fa-arrow-right" aria-hidden="true"></i>{{ r.goods.name }}</a> </li>
                                {% endfor %}

							</ul>
					</ul>
				</div>
			</div>
			    <div class="col-md-8 products-right">
                <!-- 排序 -->
{#				<div class="products-right-grid">#}
{#					<div class="products-right-grids">#}
{#						<div class="sorting">#}
{#							<select id="country" onchange="order(this)" class="frm-field required sect">#}
{#								<option value="default">默认排序</option>#}
{#								<option value="sale_top">按-销量---降序</option>#}
{#								<option value="sale_top_reverse">按---销量-升序</option>#}
{#								<option value="price_top">按-价格---降序</option>#}
{#								<option value="price_top_reverse">按---价格-升序</option>#}
{#							</select>#}
{#						</div>#}
{#						<div class="sorting-left">#}
{#							<select id="country1" onchange="change_country(this.value)" class="frm-field required sect">#}
{#								<option value="null">Item on page 9</option>#}
{#								<option value="null">Item on page 18</option>#}
{#								<option value="null">Item on page 32</option>#}
{#								<option value="null">All</option>#}
{#							</select>#}
{#						</div>#}
{#						<div class="clearfix"> </div>#}
{#					</div>#}
{#				</div>#}
                <!-- //排序 -->


{% block goods %}
一共 {{ len }} 条结果：
<div class="agile_top_brands_grids">
        {% if good_list %}
        {% for good in page_list %}
					<div class="col-md-4 top_brand_left b_margin">
						<div class="hover14 column">
							<div class="agile_top_brand_left_grid">
                                <!-- 热卖页面等，需要用到右上角标签图片 -->
								<div class="agile_top_brand_left_grid_pos">
									<img src="../../../static/home/images/{{ good|get_right_top }}.png" alt=" " class="img-responsive">
								</div>
								<div class="agile_top_brand_left_grid1">
									<figure>
										<div class="snipcart-item block">
											<div class="snipcart-thumb">
												<a href="/detail?id={{ good.id }}">
                                                    <img class="show_img" src="../../../static/media/goods_img/{{ good.sort }}_{{ good.id }}.png" onerror="this.src='../../../static/media/goods_img/default.jpg'">
                                                </a>
                                                        <p>{{ good.name }}</p>
                                                    <h4>￥ {{ good.sale_price }}</h4>
{#                                                    <h4> {{ good.sale }} 折扣价<span>原价</span></h4>#}
											</div>
										</div>
									</figure>
								</div>
							</div>
						</div>
					</div>
        {% endfor %}
        {% else %}
            暂无结果
        {% endif %}
						<div class="clearfix"> </div>
				</div>
{% endblock goods%}

            <!-- 页码选择菜单 -->
				<nav class="numbering">
                        <ul class="pagination paging">
                        {#如果有上一页#}
                        {% if page_list.has_previous %}
                            <li class="previous"><a href="{% if flag >= 0 %}?{{ key }}={{ value }}&{% else %}?{% endif %}page={{ page_list.previous_page_number }}">«</a></li>
                        {% else %}
                            <li class="previous disabled"><a>«</a></li>
                        {% endif %}

                        {#输出页码#}
                        {% for num in paginator.page_range %}
                            {% if num == current_page %}
                                <li class="item active"><a href="{% if flag >= 0 %}?{{ key }}={{ value }}&{% if flag == 2 %}{{ key2 }}={{ value2 }}&{% endif %}{% else %}?{% endif %}page={{ num }}">{{ num }}</a></li>
                            {% else %}
                                <li class="item"><a href="{% if flag >= 0 %}?{{ key }}={{ value }}&{% if flag == 2 %}{{ key2 }}={{ value2 }}&{% endif %}{% else %}?{% endif %}page={{ num }}">{{ num }}</a></li>
                            {% endif %}
                        {% endfor %}

                        {#如果有下一页#}
                        {% if page_list.has_next %}
                            <li class="next"><a href="{% if flag >= 0 %}?{{ key }}={{ value }}&{% if flag == 2 %}{{ key2 }}={{ value2 }}&{% endif %}{% else %}?{% endif %}page={{ page_list.next_page_number }}">»</a></li>
                        {% else %}
                            <li class="previous disabled"><a aria-label="Next"><span aria-hidden="true">»</span></a></li>
                        {% endif %}
                    </ul>
				</nav>
            <!-- //页码选择菜单 -->
			</div>
			<div class="clearfix"> </div>
		</div>
	</div>
{% endblock %}

{% block js %}
    <script>
        //(function () {
//
        //    function order(obj) {
        //        console.log($(obj).val())
        //   }
        //});
    </script>
{% endblock %}

SuperMarket/templates/home/detail.html
{% extends "home/all.html" %}
{% load my_tags %}
{% block title %}
-
    {% if good.sort == 0 %}
    零食饮料
    {% elif good.sort == 1 %}
    生鲜果蔬
    {% elif good.sort == 2 %}
    粮油副食
    {% elif good.sort == 3 %}
    清洁用品
    {% elif good.sort == 4 %}
    家居家电
    {% endif %}
{% endblock %}

{% block loc %}
    {% if good.sort == 0 %}
    零食饮料
    {% elif good.sort == 1 %}
    生鲜果蔬
    {% elif good.sort == 2 %}
    粮油副食
    {% elif good.sort == 3 %}
    清洁用品
    {% elif good.sort == 4 %}
    家居家电
    {% endif %}
{% endblock loc %}

{% block main %}
<div class="products">
		<div class="container">
			<div class="agileinfo_single">

				<div class="col-md-4 agileinfo_single_left">
					<img id="example" src="../../../static/media/goods_img/{{ good.sort }}_{{ good.id }}.png" onerror="this.src='../../../static/media/goods_img/default.jpg'"  class="img-responsive show_detail_img">
				</div>
				<div class="col-md-8 agileinfo_single_right">
				<h2>{{ good.name }}</h2>
					<div class="w3agile_description">
                        <br>
						<h4>详细信息 :</h4>
						<p>重量：{{ good.weight }} g<br>
                            销量：{{ good.record_set.all|get_all_sale }}<br>
                            生产日期：{{ good.produce_date|date:'Y-m-d' }}<br>
                            剩余保质期：{% get_limit_period good.produce_date good.limit_date %}
                        </p>
                        <br>
                            <h4>所在超市 :</h4>
                            <p>{% record_get_location good.record_set.all 1 %}
                            </p>
					</div>
					<div class="snipcart-item block">
						<div class="snipcart-thumb agileinfo_single_right_snipcart">
							<h4 class="m-sing">零售价：
                                {% if good.lower > 0 %}
                                    ￥{% get_cheap_price good.sale_price good.lower %}

                                    <span>￥{{ good.sale_price }}</span>
                                    {% else %}
                                    ￥{{ good.sale_price }}
                                {% endif %}
                            </h4>
						</div>
					</div>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>


<!-- new -->
	<div class="newproducts-w3agile">
		<div class="container">
			<h3>本周上新</h3>
				<div class="agile_top_brands_grids">
                    {% for r in new_list %}

					<div class="col-md-3 top_brand_left-1">
						<div class="hover14 column">
							<div class="agile_top_brand_left_grid">
								<div class="agile_top_brand_left_grid_pos">
									<img src="../../../static/home/images/offer.png" alt=" " class="img-responsive">
								</div>
								<div class="agile_top_brand_left_grid1">
									<figure>
										<div class="snipcart-item block">
											<div class="snipcart-thumb">
												<a href="/detail?id={{ r.goods.id }}">
                                                    <img class="show_img" src="../../../static/media/goods_img/{{ r.goods.sort }}_{{ r.goods.id }}.png" onerror="this.src='../../../static/media/goods_img/default.jpg'">
                                                </a>
												<p>{{ r.goods.name }}</p>
                                                <p>{{ r.date|get_sub_date }}</p>
													<h4>￥ {{ r.goods.sale_price }}</h4>
											</div>
										</div>
									</figure>
								</div>
							</div>
						</div>
					</div>

                    {% endfor %}
						<div class="clearfix"> </div>
				</div>
		</div>
	</div>
<!-- //new -->
{% endblock %}

SuperMarket/templates/home/feedback.html
{% extends "home/all.html" %}

{% block title %}
反馈 &amp; 评价
{% endblock title%}

{% block loc %}
反馈 &amp; 评价
{% endblock loc %}

{% block main %}
<!-- //breadcrumbs -->

<!-- about -->
<div class="about">
	<div class="container">
		<div class=" w3_agileits_contact_grid_right" style="padding-left: 64px" >
				<h2 class="w3_agile_header">反馈 &amp; 评价</h2>

				<form action="/send_feedback/" method="post">
                    {% csrf_token %}
					<span class="input input--ichiro">
						<input class="input__field input__field--ichiro" type="text" id="input-25" name="Name" placeholder=" " required="">
						<label class="input__label input__label--ichiro" for="input-25">
							<span class="input__label-content input__label-content--ichiro">称呼</span>
						</label>
					</span>
					<span class="input input--ichiro">
						<input class="input__field input__field--ichiro" type="text" id="input-26" name="Contact" placeholder=" " required="">
						<label class="input__label input__label--ichiro" for="input-26">
							<span class="input__label-content input__label-content--ichiro">联系方式</span>
						</label>
					</span>
					<textarea name="Message" placeholder="留下您宝贵的意见与建议..." required=""></textarea>
					<input type="submit" value="提  交" onclick="alert('感谢您的反馈与评价！您可以在关于页面看到所有的消息。')">
				</form>
			</div>
				<div class="clearfix"> </div>
	</div>
</div>
	<!-- //about -->
{% endblock main%}